# https://hub.docker.com/r/linuxserver/overseerr
---
version: "2.1"
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1027
      - PGID=100
      - TZ="Europe/Zurich"
    volumes:
      - /autopirate/config/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped