# https://hub.docker.com/r/linuxserver/plex
#
# To allow local playback, add local LAN segments and the server's IP address and name in the Plex settings:
#
# Settings > Network > Custom server access URLs: https://192.168.1.28:32400,https://autopirate.fqp.ch:32400
# Settings > Network > List of IP addresses and networks that are allowed without authentication: 10.10.0.0/16,192.168.1.0/24,172.16.0.0/12
#
---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1027
      - PGID=100
      - TZ="Europe/Zurich"
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /autopirate/config/plex:/config
      - /autopirate/media/tvseries:/tv
      - /autopirate/media/movies:/movies
      - /autopirate/downloads/plex-transcode:/transcode
    restart: unless-stopped