
# https://hub.docker.com/r/linuxserver/qbittorrent


---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - /autopirate/config:/config
      - /autopirate/downloads:/downloads
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
