# https://hub.docker.com/r/linuxserver/sonarr
---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1027
      - PGID=100
      - TZ="Europe/Zurich"
    volumes:
      - /autopirate/config/sonarr:/config
      - /autopirate/media/tvseries:/tvseries 
      - /autopirate/downloads:/downloads 
    ports:
      - 8989:8989
    restart: unless-stopped

