- Media:
  - Jellyfin:
      description: Media server, user flieder
      href: http://autopirate.fqp.ch:8096/
      siteMonitor: http://autopirate.fqp.ch:8096/
      icon: jellyfin.png
  - Plex:
      description: Media server, user flieder10@gmail.com
      href: http://autopirate.fqp.ch:32400/web
      siteMonitor: http://autopirate.fqp.ch:32400/
      icon: plex.png
  - Calibre:
      description: Ebook server, user flieder10@gmail.com
      href: http://autopirate.fqp.ch:8083
      siteMonitor: http://autopirate.fqp.ch:8083
      icon: calibre.png
- Autopirate:
  - Overseerr:
      description: Media discovery
      href: http://autopirate.fqp.ch:5055
      siteMonitor: http://autopirate.fqp.ch:5055
      icon: overseerr.png
  - Radarr:
      description: Movie collection manager
      href: http://autopirate.fqp.ch:7878
      siteMonitor: http://autopirate.fqp.ch:7878
      icon: radarr.png
  - Sonarr:
      description: TV show collection manager
      href: http://autopirate.fqp.ch:8989
      siteMonitor: http://autopirate.fqp.ch:8989
      icon: sonarr.png
  - Prowlarr:
      description: Indexer manager/proxy
      href: http://autopirate.fqp.ch:9696
      siteMonitor: http://autopirate.fqp.ch:9696
      icon: prowlarr.png
  - qBittorrent:
      description: Torrent client
      href: http://autopirate.fqp.ch:8080
      siteMonitor: http://autopirate.fqp.ch:8080
      icon: qbittorrent.png
      widget:
        type: qbittorrent
        url: http://autopirate.fqp.ch:8080
        # username: admin

- SmartHome:
  - Home Assistant:
      description: Home automation
      href: http://has.fqp.ch:8123
      siteMonitor: http://has.fqp.ch:8123
      icon: home-assistant.png
#   - Viseron:
#       description: Network video recorder
#       href: http://nano.fqp.ch:8888
#       siteMonitor: http://nano.fqp.ch:8888
#       icon: viseron.png
#   - Shinobi:
#       description: Network video recorder
#       href: http://nano.fqp.ch:8080
#       siteMonitor: http://nano.fqp.ch:8080
#       icon: shinobi.png
#   - Picam:
#       description: Pi noir cam
#       href: http://picam.fqp.ch:8889/cam/
#       siteMonitor: http://picam.fqp.ch:8889/cam/
#       icon: unifi-protect.png
  - Grafana:
      description: Monitoring
      href: https://grafana.fqp.ch/
      siteMonitor: https://grafana.fqp.ch/
      icon: grafana.png
#   - Kibana:
#       description: Security incident and event management
#       href: https://kibana.fqp.ch:5601
#       siteMonitor: https://kibana.fqp.ch:5601
#       icon: kibana.png
  - PgAdmin:
      description: SQL database manager
      href: https://postgres.fqp.ch
      siteMonitor: https://postgres.fqp.ch
      icon: pgadmin.png
  - QR Code:
      description: Local files with QR code
      href: https://qrcode.fqp.ch/
      siteMonitor: https://qrcode.fqp.ch/health
      icon: /icons/qr-code-125.svg
  - NVR Viewer:
      description: Viewer for network video recorders
      href: https://nvrv.fqp.ch/
      siteMonitor: https://nvrv.fqp.ch/health
      icon: unifi-protect.png 
  - Webcam Carport:
      description: Reolink Cx410
      href: https://10.10.5.20/
      siteMonitor: https://10.10.5.20/
      icon: /icons/reolink.svg  
  - Webcam Garden:
      description: Reolink Cx410W
      href: https://10.10.5.21/
      siteMonitor: https://10.10.5.21/
      icon: /icons/reolink.svg  

- Infra:
  - Dagobert:
      description: Virtual NAS
      href: https://dagobert.fqp.ch
      siteMonitor: https://dagobert.fqp.ch
      icon: truenas.png  
#   - Jabba:
#       description: Backup NAS
#       href: http://jabba.fqp.ch:5000
#       siteMonitor: http://jabba.fqp.ch:5000
#       icon: synology-dsm.png
  - pfSense:
      description: Legacy virtual firewall
      href: https://pfsense.fqp.ch
      siteMonitor: https://pfsense.fqp.ch
      icon: pfsense.png
  - opnSense:
      description: Virtual firewall
      href: https://10.10.0.1/
      siteMonitor: https://10.10.0.1/
      icon: opnsense.png
  - Pi Hole:
      description: Network-wide ad blocking
      href: http://pi.hole/admin/index.php
      siteMonitor: http://pi.hole/admin/index.php
      icon: pi-hole.png
  - Unifi:
      description: Network controller
      href: https://unifi.fqp.ch
      siteMonitor: https://unifi.fqp.ch
      icon: unifi.png
  - Zbox PVE:
      description: Hypervisor node
      href: https://zbox.fqp.ch:8006
      siteMonitor: https://zbox.fqp.ch:8006
      icon: https://play-lh.googleusercontent.com/TT36Nsjyt0Yn8eyPAXuNK0bJsXmryP9ovsp7qdOy9sulYlr7v2Le5Ckf0I9S3AiaaXs=w480-h960
  - Heimdall PVE:
      description: Hypervisor node
      href: https://heimdall.fqp.ch:8006
      siteMonitor: https://heimdall.fqp.ch:8006
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/proxmox-light.png
