- Media:
  - Jellyfin:
      description: Media server, user flieder
      href: http://autopirate.local:8096/
      siteMonitor: http://autopirate.local:8096/
      icon: jellyfin.png
  - Plex:
      description: Media server, user flieder10@gmail.com
      href: http://autopirate.local:32400/web
      siteMonitor: http://autopirate.local:32400/
      icon: plex.png
  - Calibre:
      description: Ebook server, user flieder10@gmail.com
      href: http://autopirate.local:8083
      siteMonitor: http://autopirate.local:8083
      icon: calibre.png
- Autopirate:
  - Overseerr:
      description: Media discovery
      href: http://autopirate.local:5055
      siteMonitor: http://autopirate.local:5055
      icon: overseerr.png
  - Radarr:
      description: Movie collection manager
      href: http://autopirate.local:7878
      siteMonitor: http://autopirate.local:7878
      icon: radarr.png
  - Sonarr:
      description: TV show collection manager
      href: http://autopirate.local:8989
      siteMonitor: http://autopirate.local:8989
      icon: sonarr.png
  - Prowlarr:
      description: Indexer manager/proxy
      href: http://autopirate.local:9696
      siteMonitor: http://autopirate.local:9696
      icon: prowlarr.png
  - qBittorrent:
      description: Torrent client
      href: http://autopirate.local:8080
      siteMonitor: http://autopirate.local:8080
      icon: qbittorrent.png
      widget:
        type: qbittorrent
        url: http://autopirate.local:8080
        # username: admin

- SmartHome:
  - Home Assistant:
      description: Home automation
      href: http://has.local:8123
      siteMonitor: http://has.local:8123
      icon: home-assistant.png
#   - Viseron:
#       description: Network video recorder
#       href: http://nano.local:8888
#       siteMonitor: http://nano.local:8888
#       icon: viseron.png
#   - Shinobi:
#       description: Network video recorder
#       href: http://nano.local:8080
#       siteMonitor: http://nano.local:8080
#       icon: shinobi.png
#   - Picam:
#       description: Pi noir cam
#       href: http://picam.local:8889/cam/
#       siteMonitor: http://picam.local:8889/cam/
#       icon: unifi-protect.png
  - Grafana:
      description: Monitoring
      href: https://grafana.local/
      siteMonitor: https://grafana.local/
      icon: grafana.png
#   - Kibana:
#       description: Security incident and event management
#       href: https://kibana.local:5601
#       siteMonitor: https://kibana.local:5601
#       icon: kibana.png
  - PgAdmin:
      description: SQL database manager
      href: https://postgres.local
      siteMonitor: https://postgres.local
      icon: pgadmin.png
  - QR Code:
      description: Local files with QR code
      href: https://qrcode.local/
      siteMonitor: https://qrcode.local/health
      icon: /icons/qr-code-125.svg
  - NVR Viewer:
      description: Viewer for network video recorders
      href: https://nvrv.local/
      siteMonitor: https://nvrv.local/health
      icon: unifi-protect.png 
  - Webcam Carport:
      description: Reolink Cx410
      href: https://cx410.local/
      siteMonitor: https://cx410.local/
      icon: /icons/reolink.svg  
  - Webcam Garden:
      description: Reolink Cx410W
      href: https://10.10.5.21/
      siteMonitor: https://10.10.5.21/
      icon: /icons/reolink.svg  

- Infra:
  - Dagobert:
      description: Virtual NAS
      href: https://dagobert.local
      siteMonitor: https://dagobert.local
      icon: truenas.png  
  - pfSense:
      description: Legacy virtual firewall
      href: https://pfsense.local
      siteMonitor: https://pfsense.local
      icon: pfsense.png
  - opnSense:
      description: Virtual firewall
      href: https://10.10.8.1/
      siteMonitor: https://10.10.8.1/
      icon: opnsense.png
  - Pi Hole:
      description: Network-wide ad blocking
      href: http://pi.hole/admin/
      siteMonitor: http://pi.hole/admin/login
      icon: pi-hole.png
  - Prism: 
      description: Service management
      href: http://prism:8000
      siteMonitor: http://prism:8000
      icon: photoprism-light.png
  - Unifi:
      description: Network controller
      href: https://unifi.local
      siteMonitor: https://unifi.local
      icon: unifi.png
  - Ansible:
      description: Ansible Semaphore
      href: http://ansible:3000
      siteMonitor: http://ansible:3000
      icon: ansible.png
  - Zbox PVE:
      description: Hypervisor node
      href: https://zbox.local:8006
      siteMonitor: https://zbox.local:8006
      icon: https://play-lh.googleusercontent.com/TT36Nsjyt0Yn8eyPAXuNK0bJsXmryP9ovsp7qdOy9sulYlr7v2Le5Ckf0I9S3AiaaXs=w480-h960
  - Heimdall PVE:
      description: Hypervisor node
      href: https://heimdall.local:8006
      siteMonitor: https://heimdall.local:8006
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/proxmox-light.png
